# Generated by Django 5.2.14 on 2026-05-20 15:04

import django.core.validators
import django_openuser.models
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Username must be between 4 and 150 characters. Letters and digits only.', max_length=150, unique=True, validators=[django.core.validators.MinLengthValidator(4), django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Enter a valid username. Letters and digits only.', 'invalid')], verbose_name='username')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to=django_openuser.models.user_avatar_upload_path)),
                ('firstname', models.CharField(max_length=150, verbose_name='firstname')),
                ('lastname', models.CharField(max_length=150, verbose_name='lastname')),
                ('phonenumber', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Contact phone number', max_length=128, null=True, region='FI', verbose_name='phone number')),
                ('address', models.CharField(blank=True, max_length=50, null=True, verbose_name='address')),
                ('postal_code', models.CharField(blank=True, max_length=5, null=True, verbose_name='postal code')),
                ('city', models.CharField(max_length=50, null=True, verbose_name='city')),
                ('info', models.TextField(blank=True, max_length=500, verbose_name='info')),
                ('join_date', models.DateTimeField(auto_now_add=True, verbose_name='join date')),
                ('last_online', models.DateTimeField(auto_now_add=True, verbose_name='last online')),
                ('member_id', models.CharField(blank=True, unique=True, verbose_name='member id')),
                ('is_staff', models.BooleanField(default=False, verbose_name='is staff')),
                ('is_active', models.BooleanField(default=False, verbose_name='is active')),
                ('is_private', models.BooleanField(default=True, null=True, verbose_name='is private')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
