# Generated by Django 5.2.14 on 2026-05-30 10:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_openuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_online',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last online'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'An user with that username already exists.'}, help_text='Username must be between 4 and 150 characters. Letters and digits only.', max_length=150, unique=True, validators=[django.core.validators.MinLengthValidator(4), django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Enter a valid username. Letters and digits only.', 'invalid')], verbose_name='username'),
        ),
    ]
