# Generated by Django 5.2.14 on 2026-05-30 13:44

import django.utils.timezone
import django_openuser.models
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_openuser', '0002_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='address',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='address'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='city',
            field=models.CharField(default='', max_length=50, verbose_name='city'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_private',
            field=models.BooleanField(default=True, verbose_name='is private'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_online',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='last online'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phonenumber',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default='', help_text='Contact phone number', max_length=128, region='FI', verbose_name='phone number'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='postal_code',
            field=models.CharField(blank=True, default='', max_length=5, verbose_name='postal code'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, default='', upload_to=django_openuser.models.user_avatar_upload_path),
            preserve_default=False,
        ),
    ]
