# Generated by Django 5.2.14 on 2026-05-30 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_openuser', '0003_alter_customuser_address_alter_customuser_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='last_online',
            field=models.DateTimeField(auto_now_add=True, verbose_name='last online'),
        ),
    ]
